package main

import (
	"bytes"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// screenshotDirs hold every still the site shows of the TUI itself: the
// ones regenerated by hand, from tapes/out/ or a capture. The icons and the
// logo are drawn once and are not held to this, and ImageOptim leaves the
// two favicons truecolour anyway.
var screenshotDirs = []string{"docs/screenshots", "docs/themes"}

// Every screenshot the site serves is a 256-colour palette. They are flat
// terminal colours, so quantising them costs nothing visible and most of
// their weight: on 2026-09-30 ImageOptim, with lossy compression on, took
// the ten carousel shots from 5.17 MB to 1.84 MB at SSIM ≥ 0.9986 on every
// one, and Chrome decoded them six times faster (223 → 37 ms). A still
// promoted from tapes/out/ is truecolour, and nothing else would notice it
// had skipped that step.
func TestScreenshotsAreQuantized(t *testing.T) {
	signature := []byte("\x89PNG\r\n\x1a\n")
	found := 0
	for _, dir := range screenshotDirs {
		err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() || !strings.EqualFold(filepath.Ext(path), ".png") {
				return err
			}
			found++
			f, err := os.Open(path)
			if err != nil {
				return err
			}
			defer f.Close()
			// The IHDR chunk comes first: after the 8-byte signature come
			// its length and type (4+4), then width, height (4+4) and bit
			// depth (1), so the colour type is byte 25. Indexed colour is 3.
			head := make([]byte, 26)
			if _, err := io.ReadFull(f, head); err != nil || !bytes.Equal(head[:8], signature) || string(head[12:16]) != "IHDR" {
				t.Errorf("%s does not start like a PNG", path)
				return nil
			}
			if head[25] != 3 {
				t.Errorf("%s is truecolour (PNG colour type %d): run it through ImageOptim with lossy compression on, or pngquant, before committing it", path, head[25])
			}
			return nil
		})
		if err != nil {
			t.Fatalf("walk %s: %v", dir, err)
		}
	}
	if found == 0 {
		t.Fatal("found no screenshot: the check would measure nothing")
	}
}
